name: Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Run black
      env:
        PYTHONPATH: /workspace-SR004.nfs2/d.tarasov/compression_horizon/src:./src
        HF_HOME: /workspace-SR004.nfs2/.cache/huggingface
      run: |
        /home/jovyan/.mlspace/envs/compression_horizon/bin/python -m black --check .
    - name: Run ruff
      env:
        PYTHONPATH: /workspace-SR004.nfs2/d.tarasov/compression_horizon/src:./src
        HF_HOME: /workspace-SR004.nfs2/.cache/huggingface
      run: |
        /home/jovyan/.mlspace/envs/compression_horizon/bin/python -m ruff check .
    - name: Run flake8 (with no-chained-assignments plugin)
      env:
        PYTHONPATH: /workspace-SR004.nfs2/d.tarasov/compression_horizon/src:./src
        HF_HOME: /workspace-SR004.nfs2/.cache/huggingface
      run: |
        /home/jovyan/.mlspace/envs/compression_horizon/bin/python -m flake8 .
