name: Run Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Run pytest
      env:
        PYTHONPATH: ./src
        HF_HOME: /workspace-SR004.nfs2/.cache/huggingface
      run: ls -l && /home/jovyan/.mlspace/envs/compression_horizon/bin/pytest -v ./tests/
